openapi: 3.0.0
info:
  title: Athena Credit Card Acquisition API
  description: The resources that make up the Athena credit card acquisition REST API v1. If you have any problems or requests please contact
  version: "0.1.0"

servers:
  - url: http://{subdomain}.athena.com/{version}
    description: The main prod server
    variables:
      subdomain:
        default: cca
      version:
        enum:
          - v1
          - v2
        default: v1

security:
  - bearerAuth: []

paths:
  /customers:
    patch:
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: patchCustomers
      tags:
        - customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationError"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"

        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicError"

components:
  schemas:
    Customer:
      properties:
       id:
         type: "string"
       firstName:
         type: "string"
       lastName:
         type: "string"
       email:
         type: "string"
       image_url:
         type: "string"
       gender:
         type: "boolean"
       nic:
        type: "string"
       source:
        type: "string"
       contacts:
        type: "array"
        items:
          type: "string"
       address:
         type: "object"
         properties:
           address_line1:
            type: "string"
           address_line2:
            type: "string"
           city:
            type: "string"
           country:
            type: "string"
       created:
        type: "string"
       modified:
        type: "string"
    BasicError:
      properties:
         statusCode:
           type: "string"
         name:
           type: "string"
         message:
           type: "string"
         code:
           type: "string"
         stack:
           type: "string"
    ValidationError:
      allOf:
        - $ref: '#/components/schemas/BasicError'
      properties:
         details:
           type: "object"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
